#!/usr/bin/env bash

create-symlink() {
    local source=$1
    local target=$2

    if [[ -L "$target" ]]; then
        unlink "$target"
    fi
    if [[ -f "$target" ]]; then
        echo "File exists: $target" >&2
        return 1
    fi

    if [[ ! -d $(dirname -- "$target") ]]; then
        mkdir -p -- "$(dirname -- "$target")"
    fi

    ln -s -- "$(cd "$(dirname -- "$source")" && pwd)/$(basename -- "$source")" "$target"
}

install-package() {
    local name
    local index=0
    local list=$(cat)
    local count=$(wc -l <<< "$list" | xargs)
    local home=$HOME
    local xdgconfig=${XDG_CONFIG_HOME:-$HOME/.config}
    local xdgcache=${XDG_CACHE_HOME:-$HOME/.cache}

    for name in $list; do
        let ++index
        echo "(${index}/${count}) installing ${name#*/}" >&2

        case "$name" in
            'xdg/zsh')
                create-symlink ./config/zsh/.zshenv "$home/.zshenv"
                create-symlink ./config/zsh "$xdgconfig/zsh"
                ;;
            'xdg/bash')
                create-symlink ./config/bash/.bashrc "$home/.bashrc"
                create-symlink ./config/bash "$xdgconfig/bash"
                ;;
            'xdg/tmux')
                create-symlink ./config/tmux "$xdgconfig/tmux"
                ;;
            'xdg/git/config')
                create-symlink ./config/git "$xdgconfig/git"
                ;;
            'xdg/vim')
                create-symlink ./config/.vimrc "$home/.vimrc"
                create-symlink ./config/vim "$xdgconfig/vim"
                ;;
            'xdg/nvim')
                create-symlink ./config/vim "$xdgconfig/nvim"
                ;;
            'xdg/fontconfig/fonts.conf')
                create-symlink ./config/fontconfig/fonts.conf "$xdgconfig/fontconfig/fonts.conf"
                ;;
            'xdg/nyaovim')
                create-symlink ./config/vim/nyaovim "$xdgconfig/nyaovim"
                ;;
            'dotfiles/.gvimrc')
                create-symlink ./config/.gvimrc "$home/.gvimrc"
                ;;
            'dotfiles/.vsvimrc')
                create-symlink ./config/.vsvimrc "$home/.vsvimrc"
                ;;
            'dotfiles/.ignore')
                create-symlink ./config/.ignore "$home/.ignore"
                ;;
            'xdg/phpcs/rules.php')
                create-symlink ./config/phpcs/rules.php "$xdgconfig/phpcs/rules.php"
                ;;
            'zsh/antigen')
                rm -rf -- "$xdgcache/antigen"
                git clone --depth 1 https://github.com/zsh-users/antigen "$xdgcache/antigen"
                ;;
            'vim/dein.vim')
                rm -rf -- "$xdgcache/dein/repos/github.com/Shougo/dein.vim"
                git clone --depth 1 https://github.com/Shougo/dein.vim "$xdgcache/dein/repos/github.com/Shougo/dein.vim"
                ;;
            'tmux/tpm')
                rm -rf -- "$xdgcache/tpm/plugins"
                git clone --depth 1 https://github.com/tmux-plugins/tpm "$xdgcache/tpm/plugins"
                ;;
            'junegunn/fzf')
                rm -rf -- "$xdgcache/antigen/bundles/junegunn/fzf"
                git clone --depth 1 https://github.com/junegunn/fzf "$xdgcache/antigen/bundles/junegunn/fzf"
                $xdgcache/antigen/bundles/junegunn/fzf/install --all --xdg --no-update-rc > /dev/null
                ;;
            'chriskempson/base16-iterm2')
                rm -rf -- "$xdgcache/iterm2/base16-iterm2"
                git clone --depth 1 https://github.com/chriskempson/base16-iterm2 "$xdgcache/iterm2/base16-iterm2"
                ;;
            *)
                return 1
                ;;
        esac
    done
}

install-package "$@"
