#!/usr/bin/env bash

create-symlink() {
    local source=$1
    local target=$2

    if [[ -L "$target" ]]; then
        unlink "$target"
    fi
    if [[ -f "$target" ]]; then
        echo "File exists: $target" >&2
        return 1
    fi

    if [[ ! -d $(dirname -- "$target") ]]; then
        mkdir -p -- "$(dirname -- "$target")"
    fi

    ln -s -- "$(cd "$(dirname -- "$source")" && pwd)/$(basename -- "$source")" "$target"
}

install-package() {
    local name
    local index=0
    local list=$(cat)
    local count=$(wc -l <<< "$list" | xargs)
    local home=$HOME
    local xdgconfig=${XDG_CONFIG_HOME:-$HOME/.config}
    local xdgcache=${XDG_CACHE_HOME:-$HOME/.cache}

    for name in $list; do
        let ++index
        echo "(${index}/${count}) installing ${name#*/}" >&2

        case "$name" in
            'xdg/zsh')
                create-symlink ./config/zsh/.zshenv "$home/.zshenv"
                create-symlink ./config/zsh "$xdgconfig/zsh"
                ;;
            'xdg/tmux')
                create-symlink ./config/tmux "$xdgconfig/tmux"
                ;;
            'xdg/git/config')
                create-symlink ./config/git "$xdgconfig/git"
                ;;
            'xdg/vim')
                create-symlink ./config/.vimrc "$home/.vimrc"
                create-symlink ./config/vim "$xdgconfig/vim"
                ;;
            'xdg/nvim')
                create-symlink ./config/vim "$xdgconfig/nvim"
                ;;
            'xdg/fontconfig/fonts.conf')
                create-symlink ./config/fontconfig/fonts.conf "$xdgconfig/fontconfig/fonts.conf"
                ;;
            'xdg/nyaovim')
                create-symlink ./config/vim/nyaovim "$xdgconfig/nyaovim"
                ;;
            'dotfiles/.gvimrc')
                create-symlink ./config/.gvimrc "$home/.gvimrc"
                ;;
            'dotfiles/.vsvimrc')
                create-symlink ./config/.vsvimrc "$home/.vsvimrc"
                ;;
            'xdg/phpcs/rules.php')
                create-symlink ./config/phpcs/rules.php "$xdgconfig/phpcs/rules.php"
                ;;
            'zsh/zplug')
                git clone --depth 1 https://github.com/zplug/zplug.git "$xdgcache/zplug"
                touch -- "$xdgcache/zplug/packages.zsh"
                ;;
            'vim/dein.vim')
                git clone --depth 1 https://github.com/Shougo/dein.vim.git "$xdgcache/dein/repos/github.com/Shougo/dein.vim"
                ;;
            'tmux/tpm')
                git clone --depth 1 https://github.com/tmux-plugins/tpm.git "$xdgcache/tpm/plugins"
                ;;
            *)
                exit 1
                ;;
        esac
    done
}

install-package "$@"
